controller:
  MODE: video_render
  OUTPUT_VIDEO_PATH: /home/jovyan/data/deer/d2.gif
scene:
  ANIMATED_CHARACTERS:
  - character_cfg: /home/jovyan/data/deer/char_d2/char_cfg.yaml
    motion_cfg: /home/jovyan/data/animating/config/motion/test.yaml
    retarget_cfg: /home/jovyan/data/animating/config/retarget/test.yaml
view:
  USE_MESA: true
  WINDOW_DIMENSIONS:
  - 1000
  - 1000
