end_frame_idx: null
filepath: /home/jovyan/data/animating/bvh/deerd2.bvh
forward_perp_joint_vectors:
- - LeftShoulder
  - RightShoulder
- - LeftUpLeg
  - RightUpLeg
groundplane_joint: LeftFoot
scale: 0.005
start_frame_idx: 0
up: +y
